In [1]:
import numpy as np
from sklearn import datasets
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split, StratifiedKFold
from sklearn.cluster import KMeans
from scipy.stats import mode
from sklearn.metrics import accuracy_score

In [2]:
iris = datasets.load_iris()
y = iris.target
X = StandardScaler().fit_transform(iris.data)
print(np.unique(y))

[0 1 2]


In [3]:
K = 10
cv_strat = StratifiedKFold(n_splits=K)

In [4]:
max_clusters = 20
aciertos = np.zeros(max_clusters-2, dtype='float')

for k in range(3, max_clusters+1):
    print("\n\n---------------------- clusters ",k,"----------------------\n\n")
    kmedias = KMeans(n_clusters=k, random_state = 0, n_jobs=-1)
    
    for train_index, test_index in cv_strat.split(X,y):
        X_train = X[train_index]
        y_train = y[train_index]
        X_test = X[test_index]
        y_test = y[test_index]
        
        kmedias.fit(X_train)
        moda = -1 * np.ones(k, dtype='int')
        
        for i in range(k):
            print("cluster_en_carpeta",i,k)
            # Saca la moda para cada cluster por las clases del dataset
            moda[i] = mode(y_train[np.argwhere(kmedias.labels_ == i)])[0].astype(int)
        print(moda)
        a = kmedias.predict(X_test)
        print(a)
        y_test_predict = moda[a]
        print(y_test_predict)
        aciertos[k-3] += accuracy_score(y_test,y_test_predict)
    
    # Media de aciertos para cada cluster (media de los aciertos de cada carpeta)
    aciertos[k-3] /= K
    print(k,"-->", aciertos[k-3])
print(aciertos)



---------------------- clusters  3 ----------------------


cluster_en_carpeta 0 3
cluster_en_carpeta 1 3
cluster_en_carpeta 2 3
[2 0 1]
[1 1 1 1 1 0 0 0 2 2 0 2 0 0 0]
[0 0 0 0 0 2 2 2 1 1 2 1 2 2 2]
cluster_en_carpeta 0 3
cluster_en_carpeta 1 3
cluster_en_carpeta 2 3
[0 1 2]
[0 0 0 0 0 1 2 1 1 1 2 1 2 2 2]
[0 0 0 0 0 1 2 1 1 1 2 1 2 2 2]
cluster_en_carpeta 0 3
cluster_en_carpeta 1 3
cluster_en_carpeta 2 3
[2 0 1]
[1 1 1 1 1 2 2 2 2 2 0 0 0 2 2]
[0 0 0 0 0 1 1 1 1 1 2 2 2 1 1]
cluster_en_carpeta 0 3
cluster_en_carpeta 1 3
cluster_en_carpeta 2 3
[0 1 2]
[0 0 0 0 0 2 1 1 1 1 2 2 2 2 1]
[0 0 0 0 0 2 1 1 1 1 2 2 2 2 1]
cluster_en_carpeta 0 3
cluster_en_carpeta 1 3
cluster_en_carpeta 2 3
[0 1 2]
[0 0 0 0 0 2 1 1 1 1 2 1 2 2 2]
[0 0 0 0 0 2 1 1 1 1 2 1 2 2 2]
cluster_en_carpeta 0 3
cluster_en_carpeta 1 3
cluster_en_carpeta 2 3
[2 1 0]
[2 2 2 2 2 0 0 0 1 1 0 1 1 0 0]
[0 0 0 0 0 2 2 2 1 1 2 1 1 2 2]
cluster_en_carpeta 0 3
cluster_en_carpeta 1 3
cluster_en_carpeta 2 3
[0 2 1]
[0 0 0 0 0 2 2 

cluster_en_carpeta 0 7
cluster_en_carpeta 1 7
cluster_en_carpeta 2 7
cluster_en_carpeta 3 7
cluster_en_carpeta 4 7
cluster_en_carpeta 5 7
cluster_en_carpeta 6 7
[0 2 1 2 1 0 2]
[5 0 0 0 5 4 4 4 3 2 6 6 3 2 3]
[0 0 0 0 0 1 1 1 2 1 2 2 2 1 2]
cluster_en_carpeta 0 7
cluster_en_carpeta 1 7
cluster_en_carpeta 2 7
cluster_en_carpeta 3 7
cluster_en_carpeta 4 7
cluster_en_carpeta 5 7
cluster_en_carpeta 6 7
[0 2 1 0 2 0 1]
[0 5 5 0 5 6 6 2 6 2 1 1 1 6 1]
[0 0 0 0 0 1 1 1 1 1 2 2 2 1 2]
cluster_en_carpeta 0 7
cluster_en_carpeta 1 7
cluster_en_carpeta 2 7
cluster_en_carpeta 3 7
cluster_en_carpeta 4 7
cluster_en_carpeta 5 7
cluster_en_carpeta 6 7
[0 1 2 0 1 2 2]
[0 3 3 0 0 4 1 4 4 4 2 2 6 2 2]
[0 0 0 0 0 1 1 1 1 1 2 2 2 2 2]
cluster_en_carpeta 0 7
cluster_en_carpeta 1 7
cluster_en_carpeta 2 7
cluster_en_carpeta 3 7
cluster_en_carpeta 4 7
cluster_en_carpeta 5 7
cluster_en_carpeta 6 7
[0 2 2 1 0 1 0]
[4 6 4 0 0 5 5 5 3 3 2 1 5 2 5]
[0 0 0 0 0 1 1 1 1 1 2 2 1 2 1]
7 --> 0.8733333333333336


---------

cluster_en_carpeta 0 10
cluster_en_carpeta 1 10
cluster_en_carpeta 2 10
cluster_en_carpeta 3 10
cluster_en_carpeta 4 10
cluster_en_carpeta 5 10
cluster_en_carpeta 6 10
cluster_en_carpeta 7 10
cluster_en_carpeta 8 10
cluster_en_carpeta 9 10
[2 0 1 1 2 0 1 0 2 2]
[5 1 1 5 1 3 3 2 6 2 9 0 3 3 0]
[0 0 0 0 0 1 1 1 1 1 2 2 1 1 2]
cluster_en_carpeta 0 10
cluster_en_carpeta 1 10
cluster_en_carpeta 2 10
cluster_en_carpeta 3 10
cluster_en_carpeta 4 10
cluster_en_carpeta 5 10
cluster_en_carpeta 6 10
cluster_en_carpeta 7 10
cluster_en_carpeta 8 10
cluster_en_carpeta 9 10
[2 0 1 2 0 2 1 2 0 1]
[1 8 8 1 4 2 6 2 2 6 0 0 5 0 0]
[0 0 0 0 0 1 1 1 1 1 2 2 2 2 2]
cluster_en_carpeta 0 10
cluster_en_carpeta 1 10
cluster_en_carpeta 2 10
cluster_en_carpeta 3 10
cluster_en_carpeta 4 10
cluster_en_carpeta 5 10
cluster_en_carpeta 6 10
cluster_en_carpeta 7 10
cluster_en_carpeta 8 10
cluster_en_carpeta 9 10
[0 2 2 0 1 1 2 0 1 2]
[3 0 3 0 0 4 4 5 8 4 2 1 2 2 1]
[0 0 0 0 0 1 1 1 1 1 2 2 2 2 2]
10 --> 0.9400000000000

cluster_en_carpeta 0 13
cluster_en_carpeta 1 13
cluster_en_carpeta 2 13
cluster_en_carpeta 3 13
cluster_en_carpeta 4 13
cluster_en_carpeta 5 13
cluster_en_carpeta 6 13
cluster_en_carpeta 7 13
cluster_en_carpeta 8 13
cluster_en_carpeta 9 13
cluster_en_carpeta 10 13
cluster_en_carpeta 11 13
cluster_en_carpeta 12 13
[2 0 1 1 0 2 2 2 1 1 2 0 1]
[ 1 11 11 11  1  9  9  9  8  9  5  7  6  0  0]
[0 0 0 0 0 1 1 1 1 1 2 2 2 2 2]
cluster_en_carpeta 0 13
cluster_en_carpeta 1 13
cluster_en_carpeta 2 13
cluster_en_carpeta 3 13
cluster_en_carpeta 4 13
cluster_en_carpeta 5 13
cluster_en_carpeta 6 13
cluster_en_carpeta 7 13
cluster_en_carpeta 8 13
cluster_en_carpeta 9 13
cluster_en_carpeta 10 13
cluster_en_carpeta 11 13
cluster_en_carpeta 12 13
[0 1 2 1 0 1 0 2 2 1 1 0 2]
[ 4  0  0  6  6  1 10  3  5  1  2  3  2  9 12]
[0 0 0 0 0 1 1 1 1 1 2 1 2 1 2]
cluster_en_carpeta 0 13
cluster_en_carpeta 1 13
cluster_en_carpeta 2 13
cluster_en_carpeta 3 13
cluster_en_carpeta 4 13
cluster_en_carpeta 5 13
cluster_en_c

cluster_en_carpeta 0 15
cluster_en_carpeta 1 15
cluster_en_carpeta 2 15
cluster_en_carpeta 3 15
cluster_en_carpeta 4 15
cluster_en_carpeta 5 15
cluster_en_carpeta 6 15
cluster_en_carpeta 7 15
cluster_en_carpeta 8 15
cluster_en_carpeta 9 15
cluster_en_carpeta 10 15
cluster_en_carpeta 11 15
cluster_en_carpeta 12 15
cluster_en_carpeta 13 15
cluster_en_carpeta 14 15
[0 2 1 2 2 0 0 2 2 1 0 1 1 1 2]
[ 0  6  6  6  0 14  1 14  2 13  3  8 14  8  3]
[0 0 0 0 0 2 2 2 1 1 2 2 2 2 2]
cluster_en_carpeta 0 15
cluster_en_carpeta 1 15
cluster_en_carpeta 2 15
cluster_en_carpeta 3 15
cluster_en_carpeta 4 15
cluster_en_carpeta 5 15
cluster_en_carpeta 6 15
cluster_en_carpeta 7 15
cluster_en_carpeta 8 15
cluster_en_carpeta 9 15
cluster_en_carpeta 10 15
cluster_en_carpeta 11 15
cluster_en_carpeta 12 15
cluster_en_carpeta 13 15
cluster_en_carpeta 14 15
[2 0 2 1 0 0 1 1 1 2 2 0 0 1 1]
[ 5 11 11  1  1  3  6  8  6  3 10  8 10  2  9]
[0 0 0 0 0 1 1 1 1 1 2 1 2 2 2]
cluster_en_carpeta 0 15
cluster_en_carpeta 1 15


cluster_en_carpeta 0 17
cluster_en_carpeta 1 17
cluster_en_carpeta 2 17
cluster_en_carpeta 3 17
cluster_en_carpeta 4 17
cluster_en_carpeta 5 17
cluster_en_carpeta 6 17
cluster_en_carpeta 7 17
cluster_en_carpeta 8 17
cluster_en_carpeta 9 17
cluster_en_carpeta 10 17
cluster_en_carpeta 11 17
cluster_en_carpeta 12 17
cluster_en_carpeta 13 17
cluster_en_carpeta 14 17
cluster_en_carpeta 15 17
cluster_en_carpeta 16 17
[0 2 1 2 2 0 0 2 2 1 0 1 1 1 2 1 2]
[ 0  6  6  6  0 14 13 14  2 13  3 16 14  1  3]
[0 0 0 0 0 2 1 2 1 1 2 2 2 2 2]
cluster_en_carpeta 0 17
cluster_en_carpeta 1 17
cluster_en_carpeta 2 17
cluster_en_carpeta 3 17
cluster_en_carpeta 4 17
cluster_en_carpeta 5 17
cluster_en_carpeta 6 17
cluster_en_carpeta 7 17
cluster_en_carpeta 8 17
cluster_en_carpeta 9 17
cluster_en_carpeta 10 17
cluster_en_carpeta 11 17
cluster_en_carpeta 12 17
cluster_en_carpeta 13 17
cluster_en_carpeta 14 17
cluster_en_carpeta 15 17
cluster_en_carpeta 16 17
[2 0 1 1 0 2 1 2 1 1 2 1 0 0 1 2 2]
[ 4 12 12  1  1 14 

cluster_en_carpeta 0 18
cluster_en_carpeta 1 18
cluster_en_carpeta 2 18
cluster_en_carpeta 3 18
cluster_en_carpeta 4 18
cluster_en_carpeta 5 18
cluster_en_carpeta 6 18
cluster_en_carpeta 7 18
cluster_en_carpeta 8 18
cluster_en_carpeta 9 18
cluster_en_carpeta 10 18
cluster_en_carpeta 11 18
cluster_en_carpeta 12 18
cluster_en_carpeta 13 18
cluster_en_carpeta 14 18
cluster_en_carpeta 15 18
cluster_en_carpeta 16 18
cluster_en_carpeta 17 18
[2 0 2 0 1 1 2 0 1 2 2 0 1 1 2 1 2 1]
[ 1  7  1  7  7  8  8 15  4 12  6 16  9 14 17]
[0 0 0 0 0 1 1 1 1 1 2 2 2 2 1]
18 --> 0.9466666666666669


---------------------- clusters  19 ----------------------


cluster_en_carpeta 0 19
cluster_en_carpeta 1 19
cluster_en_carpeta 2 19
cluster_en_carpeta 3 19
cluster_en_carpeta 4 19
cluster_en_carpeta 5 19
cluster_en_carpeta 6 19
cluster_en_carpeta 7 19
cluster_en_carpeta 8 19
cluster_en_carpeta 9 19
cluster_en_carpeta 10 19
cluster_en_carpeta 11 19
cluster_en_carpeta 12 19
cluster_en_carpeta 13 19
cluster_en_car

cluster_en_carpeta 18 20
cluster_en_carpeta 19 20
[0 2 2 0 2 1 1 1 2 1 1 1 0 1 0 2 2 0 2 2]
[17  0 12  0  0 13 10  7  5  7  8  1 16 18  5]
[0 0 0 0 0 1 1 1 1 1 2 2 2 2 1]
cluster_en_carpeta 0 20
cluster_en_carpeta 1 20
cluster_en_carpeta 2 20
cluster_en_carpeta 3 20
cluster_en_carpeta 4 20
cluster_en_carpeta 5 20
cluster_en_carpeta 6 20
cluster_en_carpeta 7 20
cluster_en_carpeta 8 20
cluster_en_carpeta 9 20
cluster_en_carpeta 10 20
cluster_en_carpeta 11 20
cluster_en_carpeta 12 20
cluster_en_carpeta 13 20
cluster_en_carpeta 14 20
cluster_en_carpeta 15 20
cluster_en_carpeta 16 20
cluster_en_carpeta 17 20
cluster_en_carpeta 18 20
cluster_en_carpeta 19 20
[2 0 1 0 1 0 2 2 2 1 2 1 2 1 0 0 1 0 2 1]
[ 1 14  1  1 15 19  9 16  2 11  6 12 18 10  6]
[0 0 0 0 0 1 1 1 1 1 2 2 2 2 2]
cluster_en_carpeta 0 20
cluster_en_carpeta 1 20
cluster_en_carpeta 2 20
cluster_en_carpeta 3 20
cluster_en_carpeta 4 20
cluster_en_carpeta 5 20
cluster_en_carpeta 6 20
cluster_en_carpeta 7 20
cluster_en_carpeta 8 20
cl